default['route53']['zones'] = []
default['route53']['zone-id']['affiliatewindow.com'] = 'Z2WF1VX28ZGEJ9'
default['route53']['zone-id']['affiliatewindow.ie'] = 'Z59VMPY3X9T1K'
default['route53']['zone-id']['affiliatewindows.com'] = 'Z2FSW5ZXEW4V7D'
default['route53']['zone-id']['awin1.com'] = 'Z2FUOO15AOJG05'
default['route53']['zone-id']['digitalwindow.com'] = 'ZYSAMBC301ODD'
default['route53']['zone-id']['dwin1.com'] = 'Z13V7VU1X44ONZ'
default['route53']['zone-id']['dwin2.com'] = 'ZA72BN6RPLRN2'
default['route53']['zone-id']['productserve.co.uk'] = 'Z2K8V7PJPCKD4W'
default['route53']['zone-id']['productserve.com'] = 'Z3DK37SNPDJYJ1'
default['route53']['zone-id']['shopwindow.com'] = 'Z1PBXATIXQ5HH5'
default['route53']['zone-id']['shrink.to'] = 'Z224HKIJHT5VM5'
default['route53']['zone-id']['tidd.ly'] = 'Z1A4Y3LML0OPS1'
default['route53']['zone-id']['voucherwindow.com'] = 'ZQE3050SGQIOQ'
default['route53']['zone-id']['zenaps.com'] = 'Z1TMT63FSJ0GIC'

